CUTECHESS_MAJOR_VERSION=1
CUTECHESS_MINOR_VERSION=2
CUTECHESS_PATCH_VERSION=0

CUTECHESS_VERSION=$${CUTECHESS_MAJOR_VERSION}.$${CUTECHESS_MINOR_VERSION}.$${CUTECHESS_PATCH_VERSION}

DEFINES += CUTECHESS_VERSION=\\\"$$CUTECHESS_VERSION\\\"
