#ifndef XIANGQIZOBRIST_H
#define XIANGQIZOBRIST_H
#include "easternzobrist.h"

namespace Chess {

class LIB_EXPORT XiangqiZobrist : public EasternZobrist
{
public:
    /*!
     * Creates a new uninitialized XiangqiZobrist object.
     *
     * \param keys An array of zobrist keys that can be used
     * instead of the random numbers generated by the Zobrist
     * class.
     */
    XiangqiZobrist(const quint64* keys = nullptr);

    // Inherited from EasternZobrist
    virtual void initialize(int squareCount,
                            int pieceTypeCount);
    virtual quint64 side() const;
    virtual quint64 piece(const Piece& piece, int square) const;

protected:
    /*!
     * Returns the number of squares the board has, including the
     * invisible "Wall" squares.
     */
    int squareCount() const;

private:
    int m_pieceIndex;
    QMutex m_mutex;
};

inline int XiangqiZobrist::squareCount() const
{
    return 256;
}

}

#endif // XIANGQIZOBRIST_H
