name: release cutechess
on:
  pull_request:
    branches: [ master ]
  push:
    tags:
      - 'v*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  LINUXDEPLOY_VERSION: "1-alpha-20251107-1"
  LINUXDEPLOY_SHA256SUM: "c20cd71e3a4e3b80c3483cef793cda3f4e990aca14014d23c544ca3ce1270b4d"
  LINUXDEPLOY_PLUGIN_QT_VERSION: "1-alpha-20250213-1"
  LINUXDEPLOY_PLUGIN_QT_SHA256SUM: "15106be885c1c48a021198e7e1e9a48ce9d02a86dd0a1848f00bdbf3c1c92724"

jobs:
    linuxrel:
        name: "${{ matrix.os }} Qt ${{ matrix.qt_version }}"
        runs-on: ${{ matrix.os }}
        permissions:
          contents: write
        strategy:
          matrix:
            qt_version: [6.8.3]
            os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                persist-credentials: false

            - name: download appimage tools
              run: |
                sudo apt install libfuse2 libxcb-cursor0
                curl -fsSLO https://github.com/linuxdeploy/linuxdeploy/releases/download/${LINUXDEPLOY_VERSION}/linuxdeploy-x86_64.AppImage
                curl -fsLSO https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/${LINUXDEPLOY_PLUGIN_QT_VERSION}/linuxdeploy-plugin-qt-x86_64.AppImage
                chmod +x linuxdeploy-*.AppImage

            - name: verify integrity of appimage tools
              run: |
                echo ${LINUXDEPLOY_SHA256SUM} linuxdeploy-x86_64.AppImage | sha256sum --check --status
                echo ${LINUXDEPLOY_PLUGIN_QT_SHA256SUM} linuxdeploy-plugin-qt-x86_64.AppImage | sha256sum --check --status
